name: fajerkaisi
favicon: null
layout_spectrum: 0.828908585710451
typography_spectrum: 0.6555520230904222
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.061469644540920854
  lightness: 0.28527135122567415
  saturation: 0.6290674055926502
  rhythmicContrast: 0.8716756929643452
purpose: []
